# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        prefer-ip-address: true
    client:
        enabled: true
        healthcheck:
            enabled: true
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://admin:admin@localhost:8761/eureka/

spring:
  application:
    name: guan-motan-service
  datasource:
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/guan?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull
          username: root
          password: guan123
  jpa:
      database : MYSQL
      show-sql : true
      hibernate:
        ddl-auto : update
        naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect : org.hibernate.dialect.MySQL5Dialect

motan:
  enabled: true
  annotation:
    package: com.guan
  registry:
    regProtocol : consul #注册中心协议
    address: 127.0.0.1:8500
    name: guan-motan-service
    connectTimeout: 30000

# Motan Protocol config

# Motan BasicService config
  protocol:
    name: motan
    id: pro_motan
  service:
    application: guan-motan-service
    exportPort: 8886
    accessLog: false
    shareChannel: true
  referer:
    requestTimeout: 30000

server:
  port: 8881

guan:
    security:
        client-authorization:
            accessTokenUri: http://uaa/oauth/token
            tokenServiceId: uaa
            clientId: internal
            clientSecret: internal
