
spring:
  application:
    name: guan-zuul
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true
    config:
      enabled: true   #默认是true --
      format: YAML    # 表示consul上面文件的格式 有四种 YAML PROPERTIES KEY-VALUE FILES
      data-key: configuration    #表示consul上面的KEY值(或者说文件的名字) 默认是data

zuul:
  routes:
    guan-motan-server:
      path: /api-a-url/**
      serviceId: guan-motan-server
  max:
    host:
      connections: 1000
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    #适用于ApacheHttpClient，如果是okhttp无效。每个服务的http客户端连接池最大连接，默认是200
    maxTotalConnections: 100000
    #适用于ApacheHttpClient，如果是okhttp无效。每个route可用的最大连接数，默认值是20
    maxPerRouteConnections: 10000
  semaphore:
  #指的是1秒时间窗口内的事务/查询/请求，semaphore.maxConcurrentRequests是一个绝对值，无时间窗口，相当于亚毫秒级的。当请求达到或超过该设置值后，其其余就会被拒绝。默认值是100
    maxSemaphores: 1000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  threadpool:
    default:
      coreSize: 10000   #线程池核心线程数
      maxQueueSize: 5000 #最大排队长度
      queueSizeRejectionThreshold: 10000 #排队线程数量阈值，默认为5，达到时拒绝

##timeout config
#hystrix:
#  threadpool:
#    default:
#      coreSize: 1000   #线程池核心线程数
#      maxQueueSize: 100 #最大排队长度
#      queueSizeRejectionThreshold: 200 #排队线程数量阈值，默认为5，达到时拒绝
#  command:
#    default:
#      circuitBreaker:
#        requestVolumeThreshold: 20 #当在配置时间窗口内达到此数量的失败后，进行短路。默认20个
#        sleepWindowInMilliseconds: 5 #短路多久以后开始尝试是否恢复，默认5s
#        #errorThresholdPercentage 出错百分比阈值，当达到此阈值后，开始短路。默认50%
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000






server:
  port: 5555