#eureka:
#    instance:
#        appname: guan-motan-client
#        instanceId: guan-motan-client:${spring.application.instance_id:${random.value}}
#        statusPageUrlPath: /info
#        healthCheckUrlPath: /health

